services:
  api:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
  database:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "54321:5432"
    volumes:
      - diployable-api-db-data:/var/lib/postgresql/data
volumes:
  diployable-api-db-data:
