on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Build application
        run: go build -v -o diployable-api ./cmd/main.go
      - name: Run tests
        run: go test -v ./...